// src/components/utils/ExerciseDefaults.js

export const defaultExercises = [
  // Chest Exercises
  {
    title: "Bench Press",
    muscleTags: ["Chest", "Triceps", "Shoulders"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    title: "Incline Dumbbell Press",
    muscleTags: ["Chest", "Shoulders"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    title: "Chest Flyes",
    muscleTags: ["Chest"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },

  // Back Exercises
  {
    title: "Deadlift",
    muscleTags: ["Back", "Hamstrings", "Glutes"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    title: "Pull-Ups",
    muscleTags: ["Back", "Biceps"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    title: "Bent-Over Rows",
    muscleTags: ["Back", "Biceps"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },

  // Shoulders Exercises
  {
    title: "Overhead Press",
    muscleTags: ["Shoulders", "Triceps"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    title: "Lateral Raises",
    muscleTags: ["Shoulders"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    title: "Front Raises",
    muscleTags: ["Shoulders"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },

  // Biceps Exercises
  {
    title: "Barbell Curls",
    muscleTags: ["Biceps"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    title: "Dumbbell Hammer Curls",
    muscleTags: ["Biceps", "Forearms"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    title: "Preacher Curls",
    muscleTags: ["Biceps"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },

  // Triceps Exercises
  {
    title: "Tricep Pushdowns",
    muscleTags: ["Triceps"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    title: "Skull Crushers",
    muscleTags: ["Triceps"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    title: "Overhead Tricep Extension",
    muscleTags: ["Triceps"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },

  // Quadriceps Exercises
  {
    title: "Squats",
    muscleTags: ["Quads", "Glutes", "Hamstrings"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    title: "Leg Press",
    muscleTags: ["Quads", "Glutes"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    title: "Lunges",
    muscleTags: ["Quads", "Glutes", "Hamstrings"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },

  // Hamstrings Exercises
  {
    title: "Romanian Deadlifts",
    muscleTags: ["Hamstrings", "Glutes"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    title: "Leg Curls",
    muscleTags: ["Hamstrings"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    title: "Good Mornings",
    muscleTags: ["Hamstrings", "Lower Back"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },

  // Glutes Exercises
  {
    title: "Hip Thrusts",
    muscleTags: ["Glutes", "Hamstrings"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    title: "Glute Bridges",
    muscleTags: ["Glutes", "Hamstrings"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    title: "Step-Ups",
    muscleTags: ["Glutes", "Quads"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },

  // Calves Exercises
  {
    title: "Standing Calf Raises",
    muscleTags: ["Calves"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    title: "Seated Calf Raises",
    muscleTags: ["Calves"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    title: "Leg Press Calf Extensions",
    muscleTags: ["Calves"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },

  // Abdominal Exercises
  {
    title: "Crunches",
    muscleTags: ["Abs"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    title: "Planks",
    muscleTags: ["Abs", "Lower Back"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    title: "Russian Twists",
    muscleTags: ["Abs", "Obliques"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },

  // Forearm Exercises
  {
    title: "Wrist Curls",
    muscleTags: ["Forearms"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    title: "Reverse Wrist Curls",
    muscleTags: ["Forearms"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    title: "Farmer's Walk",
    muscleTags: ["Forearms", "Traps"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },

  // Trapezius Exercises
  {
    title: "Shrugs",
    muscleTags: ["Traps"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    title: "Upright Rows",
    muscleTags: ["Traps", "Shoulders"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    title: "Face Pulls",
    muscleTags: ["Traps", "Shoulders"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },

  // Lower Back Exercises
  {
    title: "Hyperextensions",
    muscleTags: ["Lower Back", "Glutes"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    title: "Good Mornings",
    muscleTags: ["Lower Back", "Hamstrings"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    title: "Deadlifts",
    muscleTags: ["Lower Back", "Glutes", "Hamstrings"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },

  // Oblique Exercises
  {
    title: "Side Planks",
    muscleTags: ["Obliques", "Abs"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    title: "Woodchoppers",
    muscleTags: ["Obliques", "Abs", "Shoulders"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    title: "Bicycle Crunches",
    muscleTags: ["Obliques", "Abs"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
];
