// Unique ID generator function
const generateUniqueId = () => {
  return Date.now().toString(36) + Math.random().toString(36).substr(2, 9);
};

export const defaultExercises = [
  // Chest Exercises
  {
    id: generateUniqueId(),
    title: "Bench Press",
    muscleTags: ["Chest", "Triceps", "Shoulders"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    id: generateUniqueId(),
    title: "Incline Bench Press",
    muscleTags: ["Chest", "Shoulders", "Triceps"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    id: generateUniqueId(),
    title: "Dumbbell Flyes",
    muscleTags: ["Chest"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    id: generateUniqueId(),
    title: "Push-Ups",
    muscleTags: ["Chest", "Triceps", "Shoulders"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    id: generateUniqueId(),
    title: "Cable Crossovers",
    muscleTags: ["Chest"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },

  // Back Exercises
  {
    id: generateUniqueId(),
    title: "Pull-Ups",
    muscleTags: ["Lats", "Biceps"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    id: generateUniqueId(),
    title: "Lat Pulldowns",
    muscleTags: ["Lats", "Biceps"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    id: generateUniqueId(),
    title: "Bent-Over Rows",
    muscleTags: ["Lats", "Biceps", "Lower Back"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    id: generateUniqueId(),
    title: "Seated Cable Rows",
    muscleTags: ["Lats", "Biceps"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },

  // Shoulder Exercises
  {
    id: generateUniqueId(),
    title: "Military Press",
    muscleTags: ["Shoulders", "Triceps"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    id: generateUniqueId(),
    title: "Dumbbell Lateral Raises",
    muscleTags: ["Shoulders"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    id: generateUniqueId(),
    title: "Front Raises",
    muscleTags: ["Shoulders"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    id: generateUniqueId(),
    title: "Rear Delt Flyes",
    muscleTags: ["Shoulders"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },

  // Bicep Exercises
  {
    id: generateUniqueId(),
    title: "Barbell Curls",
    muscleTags: ["Biceps"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    id: generateUniqueId(),
    title: "Hammer Curls",
    muscleTags: ["Biceps", "Forearms"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    id: generateUniqueId(),
    title: "Concentration Curls",
    muscleTags: ["Biceps"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },

  // Tricep Exercises
  {
    id: generateUniqueId(),
    title: "Tricep Pushdowns",
    muscleTags: ["Triceps"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    id: generateUniqueId(),
    title: "Skull Crushers",
    muscleTags: ["Triceps"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    id: generateUniqueId(),
    title: "Close Grip Bench Press",
    muscleTags: ["Triceps", "Chest"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },

  // Leg Exercises (Quads and Hamstrings)
  {
    id: generateUniqueId(),
    title: "Squat",
    muscleTags: ["Quads", "Glutes", "Hamstrings"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    id: generateUniqueId(),
    title: "Leg Press",
    muscleTags: ["Quads", "Glutes"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    id: generateUniqueId(),
    title: "Lunges",
    muscleTags: ["Quads", "Glutes", "Hamstrings"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    id: generateUniqueId(),
    title: "Romanian Deadlifts",
    muscleTags: ["Hamstrings", "Glutes", "Lower Back"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },

  // Calf Exercises
  {
    id: generateUniqueId(),
    title: "Standing Calf Raises",
    muscleTags: ["Calves"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    id: generateUniqueId(),
    title: "Seated Calf Raises",
    muscleTags: ["Calves"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },

  // Abdominal Exercises
  {
    id: generateUniqueId(),
    title: "Crunches",
    muscleTags: ["Abs"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    id: generateUniqueId(),
    title: "Planks",
    muscleTags: ["Abs", "Lower Back"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    id: generateUniqueId(),
    title: "Russian Twists",
    muscleTags: ["Abs", "Obliques"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },

  // Forearm Exercises
  {
    id: generateUniqueId(),
    title: "Wrist Curls",
    muscleTags: ["Forearms"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    id: generateUniqueId(),
    title: "Reverse Wrist Curls",
    muscleTags: ["Forearms"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },

  // Trapezius Exercises
  {
    id: generateUniqueId(),
    title: "Shrugs",
    muscleTags: ["Traps"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    id: generateUniqueId(),
    title: "Upright Rows",
    muscleTags: ["Traps", "Shoulders"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },

  // Lower Back Exercises
  {
    id: generateUniqueId(),
    title: "Deadlift",
    muscleTags: ["Hamstrings", "Lower Back", "Glutes"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    id: generateUniqueId(),
    title: "Hyperextensions",
    muscleTags: ["Lower Back", "Glutes", "Hamstrings"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },

  // Oblique Exercises
  {
    id: generateUniqueId(),
    title: "Side Planks",
    muscleTags: ["Obliques", "Abs"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },

  // Additional Exercises to Reach 50
  {
    id: generateUniqueId(),
    title: "Leg Extensions",
    muscleTags: ["Quads"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    id: generateUniqueId(),
    title: "Good Mornings",
    muscleTags: ["Hamstrings", "Lower Back", "Glutes"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    id: generateUniqueId(),
    title: "Hip Thrusts",
    muscleTags: ["Glutes", "Hamstrings"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    id: generateUniqueId(),
    title: "Glute Bridges",
    muscleTags: ["Glutes", "Hamstrings"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    id: generateUniqueId(),
    title: "Step-Ups",
    muscleTags: ["Quads", "Glutes"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    id: generateUniqueId(),
    title: "Cable Pull-Throughs",
    muscleTags: ["Glutes", "Hamstrings"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },

  // Cardio Exercises
  {
    id: generateUniqueId(),
    title: "Jump Rope",
    muscleTags: ["Calves"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },

  // Additional Arm Exercises
  {
    id: generateUniqueId(),
    title: "Overhead Tricep Extension",
    muscleTags: ["Triceps"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
  {
    id: generateUniqueId(),
    title: "Preacher Curls",
    muscleTags: ["Biceps"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },

  // Additional Shoulder Exercises
  {
    id: generateUniqueId(),
    title: "Arnold Press",
    muscleTags: ["Shoulders", "Triceps"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },

  // Additional Ab Exercises
  {
    id: generateUniqueId(),
    title: "Leg Raises",
    muscleTags: ["Abs"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },

  // Additional Back Exercises
  {
    id: generateUniqueId(),
    title: "T-Bar Rows",
    muscleTags: ["Lats", "Biceps"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },

  // Additional Forearm Exercises
  {
    id: generateUniqueId(),
    title: "Farmer's Walk",
    muscleTags: ["Forearms", "Traps"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },

  // Additional Oblique Exercises
  {
    id: generateUniqueId(),
    title: "Woodchoppers",
    muscleTags: ["Obliques", "Abs", "Shoulders"],
    lastUsed: "20/10/24",
    max: 0,
    lastUsedWeight: 0,
    lastUsedReps: 0,
    notes: "",
  },
];
